[package]
name = "neos-mod-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pelite = "^0.9.0"
sha2 = "^0.10.2"
base16ct = "^0.1.1"
